services:
  wireguard:
    image: ghcr.io/jplegat/wireguard-riscv64:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - TZ=America/Los_Angeles
      - SERVERURL=spikespiegel.hopto.org
      - SERVERPORT=51822
      - PEERS=5
      - PEERDNS=1.1.1.1
      - INTERNAL_SUBNET=10.13.13.0
      - ALLOWEDIPS=0.0.0.0/0
    volumes:
      - /home/ubuntu/wireguard-server/config:/config
      - /lib/modules:/lib/modules
    ports:
      - 51822:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
